server:
  port: 8090
spring:
  application:
    name : gateway-service
zuul:
  ribbon:
    ribbon-isolation-strategy: thread
    ignored-services: '*'
    sensitive-headers: Cookie, Set-Cookie #Filtra informacion sensible
  host: #Tiempos a esperar para cada consulta
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    schoool-microservice:
      path: /api/school/** #URL del gateway en eureka
#      url: http://localhost:8080 #URL del api
      serviceId : schoool-microservice
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1111/eureka}
